import type { Flow, SiteProfile } from '../../../shared/types';

const guide = (id:string,name:string,trigger:string,...steps:string[]):Flow => ({id:`bolna-${id}`,name,trigger,steps,verified:false});

// Guides come from the signed-in UI inspected on 2026-09-18. A mapped UI is not
// an end-to-end execution test; keep verified=false until a real run is validated.
export const bolnaProfile: SiteProfile = {
  id:'bolna',name:'Bolna',domain:'platform.bolna.ai',url:'https://platform.bolna.ai/dashboard',color:'#315fe9',
  description:'Your Bolna workspace companion. Build voice agents, review calls, and prepare workflows with a clear view of every step.',
  builtIn:true,observations:0,
  instructions:`You are Nova beside the user's Bolna dashboard. Speak like a precise voice-operations teammate. Nova operates Bolna; it is not the voice agent being configured in Bolna. Do not confuse Nova's internal model configuration with the Bolna agent's visible Provider/Model fields: the latter are legitimate user settings and can be discussed.
Distinguish voice agents, graph agents, workflows, campaigns and batches. A workflow creation request does not automatically request a campaign or live calls. Suggest no-contact test steps when the user explicitly requests a test without calls.
Use the active workspace shown in the sidebar. Resolve agent, workflow, campaign or batch names before editing; ask once if ambiguous. Preserve unrelated fields. Never replace the entire prompt for a small edit without first reading the existing text. If an existing input's value is unavailable in observation, say what cannot be inspected; do not reconstruct it. Fill a requested complete draft once. Navigate actual links, tabs, comboboxes and menus; use screenshot/inspect only for missing semantic targets. Menus and scrollable inspectors need fresh observations. A route change can precede rendering; verify the new section before acting. Only the controls currently visible authorize grounding, not these guides.
Agent Studio has Agent, Intelligence, Languages, Calling, Engine, Tools and Extractions tabs. Read observed costs; model, voice and telephony changes can affect cost. Prompt variables use {variable_name}; Canvas also has {{ and @ insertion affordances. Keep placeholders intact. Default languages cannot always be removed. Edit the intended language. Adjust numeric steppers instead of guessing slider positions. A draft is not a saved agent: verify Save agent using a success message or reopening the saved record. Do not claim a real phone test from merely opening Test options.
Workflows chain calls, extractions and follow-ups. Create immediately creates an unpublished workflow, not a dialog: only use it when creation was requested. Graph canvas operations require observed node controls and ports; never invent edges. Validate before Publish. A valid draft, a published version and a running campaign are different outcomes. Campaign setup depends on a workflow/version and a contact upload. Do not fabricate contact files or destinations.
Routine inspection, filtering, navigation and preparing explicitly requested drafts need no extra permission. Classify live calls (including Get a call from agent), campaign/batch launch or scheduling, phone-number purchases, adding funds, publishing, deletions, uploads, webhook tests, changing delivery endpoints, inbound routing and access/credentials as consequential. Prepare first, then present one concrete approval with the observed agent/version, destination or recipient count, timing/timezone and cost when available. A demo request never authorizes contacting customers. Respect any visible trial restriction to verified numbers. Stop at unavailable or disabled controls. Credentials and payment entry are handled by the user; never reveal or copy them. Do not automatically repeat a possibly dispatched call or batch after a timeout.
For call reports, state the selected date range, timezone, filters, metric units and whether results are page-limited. Empty or loading data is not a zero result until the page confirms it. Use exact observed evidence for outcomes; if the account lacks agents/calls/published versions, identify that prerequisite instead of claiming success. Saved flows are optional hints, not a capability boundary.`,
  flows:[
    guide('review-agent','Review an agent','Review the current Bolna agent and explain its visible setup without changing anything.',
      'Open Agent Studio and resolve the intended agent using Search agents. Do not create an agent for a read-only review.',
      'Inspect Agent, Intelligence, Languages, Calling, Engine, Tools and Extractions as relevant. Summarize visible settings and unavailable values.',
      'Distinguish the agent cost breakdown from Nova pricing. Report draft versus saved state; do not click Get a call from agent.'),
    guide('prepare-prompt','Prepare a voice-agent prompt','Help me prepare a concise English customer-support agent prompt without starting a call.',
      'Clarify the business purpose only if it is missing. Select the requested agent or create only when asked.',
      'On Agent, prepare the welcome message and Canvas prompt once. Preserve variables and choose the intended language.',
      'Stop after drafting unless saving was requested. Verify the requested draft; saving and testing are separate actions.'),
    {...guide('create-agent','Create and save a voice agent','Create a new Bolna voice agent with the name, welcome message and prompt I provide.',
      'LIVE EXECUTED 2026-09-18: New Agent → named draft → welcome and current-language prompt → Save agent → named saved record and agent-specific Call history link. This verification covers creating a configuration, not making a call or proving conversation quality.',
      'Open Agent Studio. Search for the requested name first to prevent duplicates after an interrupted attempt. For a new object, use New Agent and verify the New Agent draft state; do not overwrite a different saved agent.',
      'Enter the requested name in the My Awesome Agent field. Bolna can show Draft has been saved successfully while editing: that is draft persistence, not proof that Save agent completed.',
      'Fill Agent Welcome Message once. Preserve any requested {variable_name} placeholders. In Canvas, identify the active language before replacing its prompt; do not replace a whole existing prompt for a small requested change.',
      'Review the name, welcome message, active-language prompt, Voice engine, routing and visible cost breakdown. Leave unrelated provider, telephony, tool and routing settings unchanged.',
      'Click Save agent once when creation/saving was requested. Observe the named agent row with Agent options, its Updated timestamp and a Call history link containing an agent ID; a toast or a generic page change alone is insufficient.',
      'If the save response is missing, search the exact name and inspect the saved record before retrying. Once saved, use the same record for later changes. Adding languages, attaching knowledge, configuring extractions and running tests are separate steps with their own verification.'),verified:true},
    guide('intelligence','Configure intelligence','Change the selected agent’s intelligence settings.',
      'Open Intelligence, inspect Provider and Model options and choose only requested compatible entries.',
      'Use numeric fields for output tokens and Temperature; inspect the multi-select knowledge-base control if requested.',
      'Review observed cost and persist only the requested configuration; verify the saved state.'),
    guide('languages','Languages and voices','Configure the agent’s language, voice and transcription.',
      'On Agent, inspect the current language chips and active Canvas text. Add Language opens Search languages; filter and choose an observed language. Verify its new chip instead of assuming Enter selected it.',
      'Adding English was observed to open a generic English prompt rather than copy the Hindi prompt. Read and configure each intended language separately; switching chips changes the Canvas text.',
      'Use Set English as default language (or the corresponding observed language control) when requested. Verify English(Default); its removal becomes unavailable and the former default gains Set as default and Remove controls.',
      'Fill each requested language prompt once, verify the exact active-language text and Save agent. Reopen the record and revisit each chip before claiming all multilingual edits persisted.',
      'Open Languages and choose the intended language before Voice provider, Model, Voice and Advanced settings.',
      'Configure Transcription provider/model and Keywords as requested. Preview welcome message only when requested; do not place a phone call.'),
    guide('calling','Calling configuration','Review calling settings and prepare the changes I request.',
      'Inspect Calling → Telephony Provider, Ambient Noise, Noise Cancellation, Voicemail Detection, DTMF and Auto Reschedule.',
      'Inbound Calling and outbound timing restrictions can affect live routing; inspect the actual fields and timezone before preparing changes.',
      'Review consequential routing changes before saving. Disabled controls are unavailable, not hidden capabilities.'),
    guide('engine','Tune conversation timing','Help me tune the agent’s response timing and interruptions.',
      'Inspect Engine → Response Rate, Endpointing, Linear delay and interruption word count.',
      'Review User Online Detection, language-specific messages, final message, silence hangup and total timeout.',
      'Change requested values using numeric controls, preserve units, and verify after save. Do not promise latency without measuring a test.'),
    guide('tools','Agent tools','Help me configure a tool for my Bolna agent.',
      'Inspect Tools: Calendar Availability, Book Appointment, Transfer Call, or Custom Function.',
      'Prepare the intended tool using observed fields. Write manually and Generate from cURL are distinct options.',
      'Ask the user to enter secrets. Review external destinations, access and live effects before saving or testing.'),
    guide('extractions','Extractions and webhooks','Review the agent’s extractions and webhook setup.',
      'Inspect Extractions → Webhook Configuration, Trigger on statuses, Extraction Library and New Category.',
      'New Category opens a Name field and a Model combobox; the inspected default was GPT 4.1 Mini. The dialog explains that category extractions share one model pass. Enter a distinct category name and inspect the current model choices.',
      'Create Category becomes available after naming. After clicking once, wait for a category visible in the agent configuration. A disabled Create Category button is an in-flight state, not creation evidence. If the response is unclear, reopen the saved agent and inspect categories before trying again.',
      'Prepare the requested extraction schema using actual category fields; do not infer a successful extraction from configuration alone.',
      'Send test transmits a payload to the configured endpoint: review the exact destination and payload scope before dispatch.'),
    {...guide('test-extraction','Create and test a structured extraction','Create an extraction with allowed answers and test it against my transcripts.',
      'LIVE EXECUTED 2026-09-18: category creation, a three-answer Pre-defined extraction and three real Bolna transcript tests. Expected and observed objectives matched: hours, consultation, other. This proves these transcript tests, not accuracy on future calls or webhook delivery.',
      'Select the saved agent → Extractions. Resolve the intended category; New Category requires Name and Model. Category extractions share one model pass. Click Create Category once and verify the named category; after an uncertain response, reopen before creating a duplicate.',
      'Within that category, Add Extraction opens Name, Extraction Prompt and Answer Type. Choose Free Text or Pre-defined for the requested schema. Preserve recipient_data placeholders such as {name} if required; never invent personal values.',
      'For Pre-defined, Add Answer creates Answer Value, Condition and Sub-option controls. Fill each distinct allowed value and its condition, including a fallback when requested. Save Extraction may be enabled before answer rows exist: inspect the schema rather than using enablement as validation. Nested sub-options were not executed in this lab.',
      'Save Extraction once and verify its named row and prompt preview under the correct category. Open Test: sample transcript buttons, Paste/Import, transcript input and model override are separate controls.',
      'Fill the intended transcript once and read it back. Leave model override off to test the category model, or select a requested override. Run Test once. Running Test clears previous results; wait for new Extraction Results before reporting.',
      'Compare objective, confidence, confidence label and reasoning against the expected result. Report mismatches; do not equate a high confidence score with correctness. The lab checked an opening-hours request, a consultation-duration request and a goodbye-only fallback. These tests do not place a phone call.'),verified:true},
    {...guide('knowledge','Knowledge base','Help me add and attach a knowledge base.',
      'Open Knowledge Base and inspect RAG ID, Source, Type, Created and Status.',
      'Add Knowledge Base offers Upload PDF or Add URL plus Language Support. Obtain the intended file or URL; do not invent a source.',
      'LIVE OBSERVED: Add URL accepted a public Bolna documentation URL with English (Default). Uploading… was followed by a table row containing its RAG ID, exact source URL, type Url and processing status. A later revisit showed processed for the same ID. Submission and processing completion are distinct outcomes.',
      'Record the new RAG ID and match both source and status before attachment. Wait for processed; do not attach or claim readiness from processing. On error, inspect the source and failure before retrying, to avoid duplicate resources.',
      'Select the intended saved agent by name/ID before Intelligence → Add knowledge base (Multi-select). The list uses checkboxes; select the intended processed source, close the list, read the source label and Save agent. Reopen the agent and verify the selection persisted. Existing unrelated knowledge selections should remain intact.',
      'Attaching a processed resource does not prove retrieval or answer quality. A separate relevant conversation test is required; public documentation used to test ingestion does not replace the user’s actual business knowledge. LIVE VERIFIED scope: public URL processing, attachment, Save agent and persisted selection after reload; PDF and retrieval answer quality remain untested.'),verified:true},
    {...guide('graph','Graph agents','Help me build or inspect a graph agent.',
      'Open Graph Agent, use Search agents, and select an existing agent if one was requested.',
      'Create offers Blank graph agent, Import graph agent, Inbound Customer Support and Order Tracking with API Tools. Creating is a mutation.',
      'LIVE CONFIGURED: Blank graph agent opens an LLM greeting marked START with zero transitions. Rename using the breadcrumb. Select a node to edit Node id and Prompt; IDs allow letters, digits and underscores and cannot start with a digit. Add node opens LLM, Static Audio and Router choices, followed by Create Node.',
      'For static audio, fill Spoken message separately for each configured language. Agent setup → Languages and Voice → Add Language does not fully configure its providers: the new English language initially had no STT/TTS provider. Choose compatible provider/model/voice entries and read them back before saving.',
      'Select the source node → Transition. Choose Transition to and Intent, Rule or Always. Intent exposes a natural-language condition. After Create transition, verify the actual Edge from source to target, its condition text and the source transition count. The edge inspector has destination, optional Label, Condition type, Condition, optional Priority and Advanced.',
      'With Nova’s side panel open, Bolna’s inspector may cover the canvas toolbar. If Validate is obstructed, use the visible Close inspector control, re-observe and then Validate. Do not click through overlays.',
      'Validate and inspect both errors and warnings. The static closing node retained a missing-spoken-message warning despite visible Hindi and English text, including after Save; its chat closing test produced no visible reply. For this demo, switching that node to LLM and filling its closing Prompt yielded All checks passed. The static-path issue remains unresolved; do not promise audio playback.',
      'Save a new graph once, then verify its graph-agent/<id> URL and saved result. The lab preserved its edge and English closing text and exposed Version history after save. An uncertain save should be checked in the agent list before creating another.',
      'Inspector → Test agent offers Get call from agent and Chat with agent. Chat opens a text input and Send; wait for the response after Agent is typing. The lab returned the configured weekday opening hours. A text test does not verify phone routing, synthesized audio or all transitions; live calling needs concrete recipient review. After the LLM closing-node recovery, a fresh chat returned the exact expected closing reply.'),verified:true},
    {...guide('workflow','Build and validate a workflow','Help me build, connect and validate a workflow.',
      'LIVE EXECUTED 2026-09-18: a named demo workflow with required reference_id text field, Start → one-minute Wait → End(success), No issues found validation, and Published version 1 confirmed in Version history. No campaign execution or call was performed in this test; other node types are not certified by it.',
      'Open Workflows, search for an existing workflow, or use Create only for an explicit creation request; it immediately creates an Untitled workflow.',
      'Click the breadcrumb name to rename, then commit and verify it. Select Start: Batch fields has Field name, Type, Required, Add field, reorder/remove, and template Download. The observed default was required mobile_number(phone); reference_id automatically uses text and its Type becomes disabled. Preserve real campaign schema unless a change was requested.',
      'Select a predecessor and use its Add node after control. Verify Adding after [name], then choose an available node. In the live test this created both the node and a visible Edge from predecessor to successor. Global Add node and connected Add node after must not be assumed equivalent.',
      'Wait offers Fixed delay or Scheduled time. For Fixed delay, fill the numeric Wait field and inspect the readback plus Unit (minutes, hours, days). A zero delay continues immediately. Verify Next node after connecting the successor; end · Unhandled is not a configured terminal outcome.',
      'Condition was disabled directly after Wait: its tooltip explains that a Condition folds into predecessor cases and needs a branching predecessor such as Agent or API request. Do not invent or force an unavailable transition. Extraction must follow its linked Agent call. Retry is the permitted cycle mechanism; these paths still need live execution tests.',
      'End requires Outcome: success, failure or neutral. Its node label becomes the termination reason. Renaming a node changed its ID and the displayed edge labels; use fresh observations after editing.',
      'Validate and wait for the Validation result. The demo displayed No issues found. Publishing is separate: review the exact draft and effects first; after authorized Publish verify Published version N and Version history marking that version Current. Version actions include View, Restore and Save as new workflow; merely seeing those options does not prove a restore succeeded.'),verified:true},
    guide('campaign','Campaign preparation','Prepare a Bolna campaign and stop before upload or launch.',
      'Open Campaigns; inspect Campaigns/Executions, name-or-ID filter, workflow/status/kind filters and the current result scope.',
      'New campaign asks for Campaign name, Workflow, Version and Contacts. Choose the published version before expecting the column template.',
      'Live preparation selected the named demo workflow and Version 1 · latest. Saving… appeared before the file control became enabled; this alone is not proof of a completed campaign. Column template · v1 downloaded a CSV with exactly reference_id, matching the published Start schema.',
      'The inspected upload accepts CSV or JSON up to 32 MB / 150,000 rows; recheck current limits. Never use actual customer contacts for an unapproved demo.',
      'Review recipients, workflow version, scheduling, timezone and cost before an upload or live launch. Verify actual campaign state once, and never blindly retry dispatch.'),
    guide('batches','Batch operations','Inspect my batches and prepare the batch action I request.',
      'Open Batches → Agent Batches. Select an agent first; Upload Batch is disabled without one. A download-template-sheet link is available.',
      'Resolve the intended agent, batch, contacts, schedule and timezone from the user and live UI.',
      'Uploading contacts, launching calls and rescheduling live work require concrete review. A prepared batch is not a dispatched batch.'),
    guide('numbers','Numbers and SIP','Review my phone numbers and SIP routing.',
      'My Numbers lists the number, answering agent, telephony provider, purchase/renewal dates and monthly rent, with unlink, Truecaller verification and delete actions.',
      'SIP Trunks → Create SIP Trunk opens Basics, Authentication, Gateways, Advanced and Review. Basics requires a trunk name and provider (Plivo, Telnyx, Twilio, Vobiz, Vonage or Custom); inspect actual defaults.',
      'Do not buy/release a number, reveal credentials or change inbound routing without concrete review; verify the actual resulting assignment.'),
    guide('calls','Call history','Find the calls I ask about and summarize the observed outcomes.',
      'Open Call History → Agent Conversations. Observed controls include Select agent, Choose Batch, search type Execution ID, search input, Refresh and rows-per-page pagination. Use only filters actually present.',
      'Inspect execution details, recordings, transcripts or extractions only when present and needed. Stop Queued Calls is consequential; Download Records may contain private data.',
      'Report observed outcome and error information. Do not volunteer customer contact details or claim to have heard a recording without accessing it.'),
    guide('analytics','Analytics and reports','Summarize my Bolna analytics for the date range I specify.',
      'Analytics offers Call Funnel and Main Dashboard, with an agent filter. The embedded Metabase dashboard has a Date filter and Download as PDF; inspect frame availability before interacting. Reports did not finish rendering during mapping: do not invent its fields.',
      'Call Funnel shows dialed, connected, human (audio), engaged (>2 user turns) and meaningful (>30s) stages. Read the selected timeframe and denominators; label empty, unavailable and filtered data correctly.',
      'Export only the requested dataset after reviewing any private information involved. Do not fabricate report values.'),
    guide('workspace','Workspace and settings','Help me find a Bolna workspace, developer or account setting.',
      'Inspect the workspace selector. DEVELOPERS contains API Keys and Documentation; SETTINGS contains Integrations and Organisation. Nested administration controls remain dependent on account permissions.',
      'Open the observed relevant setting; do not assume permission to switch organizations or change access.',
      'Leave API keys, auth tokens and payment credentials to the user. Review account, access, routing and billing changes before committing them.')
  ]
};
