import type { SiteProfile } from '../../../shared/types';

export const inngestProfile: SiteProfile = {
  id: 'inngest',
  name: 'Inngest',
  domain: 'app.inngest.com',
  url: 'https://app.inngest.com',
  color: '#3e8f57',
  description: 'Investigate durable function health with production-safe, reviewable evidence.',
  instructions: [
    'Work only in the signed-in Inngest dashboard at app.inngest.com.',
    'Treat the selected account, workspace, environment, app, function, run, event, and time range as separate scopes; verify each visible scope before drawing a conclusion.',
    'Production is strictly read-only. Never send an event, invoke a function, rerun or replay a run, cancel a run, send data to a Dev Server, deploy or sync an app, or change function configuration.',
    'Never create, reveal, rotate, copy, or modify event keys, signing keys, credentials, integrations, environment variables, or billing settings.',
    'Filters, searches, tabs, trace expansion, metrics ranges, and environment switching are navigation only; keep them read-only and do not save views or alerts unless explicitly requested in an authorized non-production scope.',
    'Event payloads, step inputs, outputs, errors, and logs may contain sensitive data. Inspect only fields needed for the user’s named investigation and never repeat secrets or unrelated customer data.',
    'Prefer run metadata, status, timestamps, function version, step names, retry counts, timing, and redacted error categories over raw payload values.',
    'Do not infer causes from a status badge alone. Correlate the observed run state with its trace, failed step, retry history, and visible error evidence.',
    'If a safe write rehearsal is requested, require an already-authorized Branch, Custom, or Local environment with synthetic events. Do not create that environment, deploy code, obtain keys, or send events as a side effect.',
    'Verify completion from current visible dashboard state and label unavailable or access-restricted evidence instead of inventing it.',
  ].join(' '),
  builtIn: true,
  observations: 0,
  flows: [
    {
      id: 'inngest-failed-run-investigation',
      name: 'Investigate a failed run',
      trigger: 'Investigate a failed Inngest function run in production without rerunning, replaying, cancelling, or sending anything.',
      verified: false,
      steps: [
        'Confirm the exact account/workspace and that the environment switcher visibly says Production; stop if either scope is ambiguous.',
        'Open Runs and apply only read-only filters for the user-named function, app, status, or time window. Do not open unrelated runs merely to find an interesting example.',
        'Open the selected failed run and record only necessary metadata: run ID or redacted suffix, function, app, status, version, and queued/started/ended timing.',
        'Inspect the trace timeline to identify the failed step, prior completed steps, retry attempts, queue or execution timing, and the visible error category. Avoid exposing unrelated event or output fields.',
        'Cross-check the error against the selected step and retry history. Distinguish direct dashboard evidence from an inferred likely cause and name any missing evidence.',
        'Summarize the observed failure boundary and a non-executing next check for an engineer. Do not press Rerun, Replay, Cancel, Send to Dev Server, or any similar action.',
      ],
    },
    {
      id: 'inngest-function-health-review',
      name: 'Review function health',
      trigger: 'Review an Inngest production function’s triggers, health metrics, and current configuration without changing or running it.',
      verified: false,
      steps: [
        'Confirm the exact account/workspace, Production environment, requested app/function, and analysis time range before inspecting metrics.',
        'Open Functions and locate only the requested function. Record its visible trigger type, app, failure rate, volume, and backlog or throughput signal where available.',
        'Open the function detail and inspect read-only configuration such as triggers, current version, concurrency, retries, or cancellation rules only when those fields are visible.',
        'Review the selected time-range metrics and recent status distribution without opening raw payloads that are unnecessary for the health question.',
        'Compare health signals carefully: call out spikes, drops, backlog, or missing data only when the chart labels and selected range visibly support them.',
        'Return an evidence-based health summary with the environment, function, time range, observed indicators, and limitations. Do not edit configuration, deploy/sync, invoke, rerun, replay, or cancel anything.',
      ],
    },
  ],
};

export const inngestLocalProfile: SiteProfile = {
  id: 'inngest-local',
  name: 'Inngest Local',
  domain: 'localhost',
  url: 'http://localhost:8288',
  color: '#3e8f57',
  description: 'Run and inspect isolated synthetic durable-function workflows on the local Inngest Dev Server.',
  instructions: [
    'Work only in the Inngest Dev Server at localhost:8288 and verify the Local environment before every action.',
    'Use only the exact synthetic Nova demo events and identifiers supplied by the user. Never copy production data, credentials, payloads, or identifiers into Local.',
    'Local synthetic event sends and their resulting runs are authorized. Do not connect, sync, deploy, or invoke any production, Branch, or Custom environment.',
    'Before sending an event, show the exact event name and JSON data in Nova and ask for confirmation. Keep synthetic true and use the requested unique final or rehearsal suffix.',
    'In the Send Event dialog, the visible contenteditable labelled Editor content is already ready for input. Use one direct fill action on that observed editor; do not click or focus it in a separate step.',
    'After sending, verify the event was accepted, open only its resulting function run, and inspect status, step names, timings, retries, and the deliberately synthetic error text where applicable.',
    'The Events table can contain older rows. Match the exact requested event name in its own visible row and open the function link from that same row; never treat an older different event as evidence that the new event is missing.',
    'Never press production-adjacent controls, create keys, reveal signing secrets, add integrations, edit billing, or expose unrelated local payloads.',
    'A successful release-review run and a deliberately failed risk-check run are both expected synthetic outcomes; do not misrepresent the deliberate failure as a product incident.',
    'Do not rerun, replay, cancel, or bulk-select runs. Create a fresh uniquely suffixed synthetic event for each rehearsal or final take.',
    'Verify completion from the current Local dashboard state and clearly separate visible facts from any inference.',
  ].join(' '),
  builtIn: true,
  observations: 0,
  flows: [
    {
      id: 'inngest-local-release-review',
      name: 'Run local release review',
      trigger: 'Send one synthetic local Northstar release-review event and verify its successful two-step function run.',
      verified: false,
      steps: [
        'Confirm the address is localhost:8288, the environment is Local, and the registered app is nova-inngest-local-demo.',
        'Open the event-send control and prepare only nova/release.review.requested with synthetic true and the user-supplied releaseId suffix.',
        'Present the exact event name and JSON data for confirmation before sending.',
        'Send the confirmed local event once and verify that the Dev Server accepted it.',
        'Open the resulting northstar-release-review run and verify successful status plus validate-release and compose-summary steps.',
        'Summarize the visible Local result and do not rerun, replay, cancel, sync, deploy, or open unrelated payloads.',
      ],
    },
    {
      id: 'inngest-local-risk-check',
      name: 'Inspect local risk-check failure',
      trigger: 'Send one deliberately failing synthetic local Northstar risk-review event and inspect its failed step without rerunning it.',
      verified: false,
      steps: [
        'Confirm localhost:8288, Local, and the nova-inngest-local-demo app before preparing the event.',
        'Open the event-send control and prepare only nova/risk.review.requested with synthetic true, mode fail, and the user-supplied reviewId suffix.',
        'Present the exact event name and JSON data for confirmation before sending.',
        'Send the confirmed local event once, match the new nova/risk.review.requested row exactly even when older release rows remain visible, then open northstar-risk-check from that same row.',
        'Verify failed status, the validate-risk step, retry evidence, and the deliberate SYNTHETIC_RISK_REVIEW_FAILURE text without exposing unrelated payloads.',
        'Explain that the failure is an intentional fixture outcome; do not rerun, replay, cancel, sync, deploy, or change configuration.',
      ],
    },
  ],
};
