import type { SiteProfile } from '../../../shared/types';

export const onyxProfile: SiteProfile = {
  id: 'onyx',
  name: 'Onyx',
  domain: 'cloud.onyx.app',
  url: 'https://cloud.onyx.app',
  color: '#4f46e5',
  description: 'Set up private synthetic workspaces without connecting models or external capabilities.',
  instructions: [
    'Work only in the signed-in Onyx workspace at cloud.onyx.app.',
    'Treat onboarding, model providers, projects, agents, uploads, knowledge, actions, web access, integrations, sharing, featuring, and workspace settings as separate scopes.',
    'Use only synthetic files or data the user explicitly identifies as private and in scope. Never browse unrelated company content.',
    'No model is connected in this account and chat is disabled. Never connect a model provider, enter provider credentials, or claim that a chat or grounded answer was tested.',
    'Use a new, take-specific synthetic name for every rehearsal or recording. Never delete, overwrite, or silently reuse an earlier Project or Agent.',
    'In the left sidebar, the unlabeled icon button immediately after the Projects heading is the New Project control. The unlabeled icon beside an existing project opens that project’s rename/delete menu and must not be used for creation.',
    'For Agent creation, use Explore Agents and its Create Agent control; never use an existing Agent’s overflow menu.',
    'Keep Agent knowledge, web access, actions, integrations, sharing, and featuring disabled. The live Agent form does not support direct file upload; do not work around that boundary.',
    'Before uploading, confirm the visible filename is the intended synthetic fixture. Never enter credentials, tokens, personal data, or secrets.',
    'Project and Agent creation change workspace state: summarize the name, instructions, privacy, file or knowledge scope, and enabled capabilities before the final save, and use the normal approval boundary.',
    'Do not send chat messages, test conversation starters, invoke actions, connect external sources, invite users, feature an Agent, or broaden visibility as a side effect of a rehearsal.',
    'Verify completion from visible Onyx state; do not rely on remembered labels or hardcoded generated answers.',
  ].join(' '),
  observations: 0,
  builtIn: true,
  flows: [
    {
      id: 'onyx-private-project',
      name: 'Create a private review project',
      trigger: 'Create a new take-specific private Onyx project, add narrow synthetic-only instructions, and upload only my approved synthetic launch brief.',
      verified: false,
      steps: [
        'Confirm onboarding still shows no connected model and chat remains unavailable. Do not open a provider connection or credential form.',
        'Use the unlabeled New Project icon immediately after the Projects heading, not the unlabeled overflow icon beside an existing project. Prepare a new private project using the exact take-specific synthetic suffix from the rehearsal plan; do not reuse or delete an earlier project.',
        'Set narrow instructions that permit only the approved synthetic launch brief and prohibit external knowledge, web access, actions, and unrelated workspace data.',
        'Review the visible project name, instructions, and private access before the final create action, then proceed through the normal approval boundary.',
        'In the new project, upload exactly the user-confirmed synthetic launch brief and no other file; wait for the visible processing state to report completion.',
        'Return to Projects, reopen the newly created item, and verify its visible project ID, exact name/suffix, private state, instructions, filename, and completed processing state.',
        'Stop without opening chat, connecting a model, sharing the project, invoking an action, or deleting any earlier project.',
      ],
    },
    {
      id: 'onyx-private-agent',
      name: 'Create a capability-disabled agent',
      trigger: 'Create a new take-specific private Onyx agent with synthetic metadata and every external capability disabled.',
      verified: false,
      steps: [
        'Confirm no model is connected, then open Agent creation and use the exact take-specific synthetic suffix from the rehearsal plan; do not reuse or delete an earlier Agent.',
        'Enter the approved synthetic name, description, narrow non-executing instructions, and conversation starter without entering secrets or real organization data.',
        'Keep Knowledge empty because direct file upload is unavailable in this form; do not add a connector, document set, or external source.',
        'Inspect every capability and visibility control. Keep actions, web access, integrations, sharing, and featuring off so the Agent remains private and non-executing.',
        'Review the visible name, description, instructions, conversation starter, empty knowledge scope, privacy, and disabled capabilities before saving; proceed through the normal approval boundary.',
        'Return to the Agent list, reopen the newly saved item, and verify its visible Agent ID, exact name/suffix, all text fields, empty knowledge, private state, and disabled capabilities.',
        'Stop without starting chat, testing the conversation starter, connecting a model, sharing or featuring the Agent, or deleting any earlier Agent.',
      ],
    },
  ],
};
