import {describe,it,expect} from 'vitest';
import {makeClarification,validateAnswers} from '../BE/src/agent/clarification';
import type {Action} from '../shared/types';
const question={id:'purpose',label:'What should it do?',description:'',type:'single_choice' as const,required:true,placeholder:'',options:[{label:'Wait and finish',description:'A no-contact draft'},{label:'Another sequence',description:''}]};
const action:Action={kind:'ask',ref:null,url:null,value:null,x:null,y:null,risk:'read',summary:'Set up your workflow',clarification:{title:'Your workflow',description:'A few details before building.',questions:[question]}};
const card=()=>makeClarification(structuredClone(action),s=>s);
describe('task question cards',()=>{
 it('creates unique card IDs and accepts custom answers',()=>{const a=card();expect(a.id).not.toBe(card().id);expect(validateAnswers(a,[{questionId:'purpose',values:[' Custom sequence ']}]).text).toContain('What should it do?: Custom sequence');});
 it('rejects missing, duplicate, unknown and multiple single-choice answers',()=>{const a=card();for(const answers of [[],[{questionId:'purpose',values:[' ']}],[{questionId:'unknown',values:['x']}],[{questionId:'purpose',values:['x']},{questionId:'purpose',values:['y']}],[{questionId:'purpose',values:['x','y']}]])expect(()=>validateAnswers(a,answers)).toThrow();});
 it('deduplicates multi-choice answers and permits all six options plus custom',()=>{const a=card();a.questions[0].type='multi_choice';expect(validateAnswers(a,[{questionId:'purpose',values:['a',' a ','b']}]).answers[0].values).toEqual(['a','b']);expect(validateAnswers(a,[{questionId:'purpose',values:['a','b','c','d','e','f','custom']}]).answers[0].values).toHaveLength(7);});
 it('checks numeric values and optional fields',()=>{const a=card();a.questions[0].type='number';expect(()=>validateAnswers(a,[{questionId:'purpose',values:['Infinity']}])).toThrow();expect(validateAnswers(a,[{questionId:'purpose',values:['0']}]).answers[0].values).toEqual(['0']);a.questions[0].required=false;expect(validateAnswers(a,[]).answers[0].values).toEqual([]);});
 it('rejects malformed model questions',()=>{for(const transform of [(a:Action)=>a.clarification!.questions.push(question),(a:Action)=>a.clarification!.questions[0].options=[],(a:Action)=>a.clarification!.questions[0].options.push({label:'WAIT AND FINISH',description:''})]){const a=structuredClone(action);transform(a);expect(()=>makeClarification(a,s=>s)).toThrow();}});
 it('does not collect secrets through card titles, questions or choices',()=>{for(const location of ['title','label','option']){const a=structuredClone(action);if(location==='title')a.clarification!.title='Enter your API key';if(location==='label')a.clarification!.questions[0].label='Your password';if(location==='option')a.clarification!.questions[0].options[0].description='Enter your recovery phrase';expect(()=>makeClarification(a,s=>s)).toThrow(/credentials/);}});
 it('supports legacy ask messages without overlong labels',()=>{const a=makeClarification({...action,summary:'Tell me more. '.repeat(20),clarification:null},s=>s);expect(a.questions[0].label.length).toBeLessThanOrEqual(160);});
});
