import {createServer} from 'node:http';import {readFile,writeFile,mkdir} from 'node:fs/promises';import assert from 'node:assert/strict';
import {ControlledBrowser} from '../BE/src/browser/controlled';import {AgentRunner} from '../BE/src/agent/runner';import {OpenAIPlanner} from '../BE/src/providers/openai';import {config,safeError} from '../BE/src/config';import {bolnaDemoProfile} from '../BE/src/sites/bolna-demo';import type {Session} from '../shared/types';
config.headless=true;config.allowLocalTests=true;
const [agent,workflow]=await Promise.all([readFile('tests/fixtures/bolna-demo.html','utf8'),readFile('tests/fixtures/workflow.html','utf8')]);const server=createServer((req,res)=>{res.writeHead(200,{'Content-Type':'text/html'});res.end(req.url?.startsWith('/workflows')?workflow:agent)});await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));const url=`http://127.0.0.1:${(server.address() as {port:number}).port}/dashboard`;
const results:any[]=[];
try{for(const model of (process.argv.includes('--current-only')?[config.model]:[config.fastModel,config.model])){const driver=new ControlledBrowser();await driver.open(url);const session:Session={id:model,siteId:'demo',mode:'browser',status:'ready',url,title:'Demo fixture',messages:[],traces:[],steps:0,model,startedAt:Date.now()};let approvals=0;const runner=new AgentRunner(session,driver,new OpenAIPlanner(),{...bolnaDemoProfile,url,domain:'127.0.0.1'},s=>{if(s.approval){approvals++;runner.stop(false)}});const timings:any[]=[];
const run=async(name:string,command:string)=>{const start=Date.now(),steps=session.steps,calls=session.usage?.calls||0;await runner.command(command);assert.ok(name==='scope-boundary'?['ready','stopped'].includes(session.status):session.status==='ready',session.messages.at(-1)?.text);const row={name,ms:Date.now()-start,actions:session.steps-steps,calls:(session.usage?.calls||0)-calls,reply:session.messages.at(-1)?.text};timings.push(row);console.log(JSON.stringify({model,...row}));};
try{await run('welcome-card',bolnaDemoProfile.flows.find(f=>f.id==='bolna-demo-welcome')!.trigger);assert.ok(session.clarification);assert.equal(session.steps,0);const card=session.clarification!;assert.equal(card.questions.length,2);const start=Date.now();await runner.answer(card.id,card.questions.map(q=>({questionId:q.id,values:[/tone|style/i.test(q.label)?'Calm and reassuring':'Ask whether they want opening hours or consultation information.']})));assert.equal(session.status,'ready',session.messages.at(-1)?.text);assert.equal(session.progress?.actions.filter(a=>a.kind==='fill').length,1);assert.ok(session.preparedInputs?.some(p=>p.value.includes('{first_name}')));assert.match((await driver.snapshot()).text,/Saves: 1/);timings.push({name:'welcome-save',ms:Date.now()-start});
await run('intelligence',bolnaDemoProfile.flows.find(f=>f.id==='bolna-demo-intelligence')!.trigger);let snap=await driver.snapshot();assert.ok(snap.elements.some(e=>e.name==='Temperature'&&e.state?.includes('value:0.4')));assert.match(snap.text,/Saves: 2/);
await run('extraction',bolnaDemoProfile.flows.find(f=>f.id==='bolna-demo-extraction')!.trigger);assert.match((await driver.snapshot()).text,/objective: consultation/);assert.match((await driver.snapshot()).text,/Extraction tests: 1/);
await run('campaign-card','Help me prepare a campaign. Ask for its name, workflow/version and file source before changing anything. Do not launch.');assert.ok(session.clarification);assert.equal(session.progress?.actions.length,0);assert.equal(approvals,0);
await run('workflow',bolnaDemoProfile.flows.find(f=>f.id==='bolna-demo-workflow')!.trigger);snap=await driver.snapshot();assert.match(snap.text,/No issues found/);assert.ok(session.progress?.settings.some(s=>s.name==='Wait'&&s.state.includes('value:2')));assert.equal(session.progress?.reloads,0);assert.equal(approvals,0);results.push({model,ok:true,timings,usage:session.usage});}
catch(error){results.push({model,ok:false,error:safeError(error),timings,traces:session.traces.slice(-15),messages:session.messages});console.log(JSON.stringify(results.at(-1),null,2));process.exitCode=1;}finally{await runner.close();}}
}finally{await mkdir('artifacts/bolna/founder-demo',{recursive:true});await writeFile(`artifacts/bolna/founder-demo/${process.argv.includes('--current-only')?'remount-regression':'model-fixture-comparison'}.json`,JSON.stringify({at:new Date().toISOString(),scope:'Isolated fictional UI; not live Bolna',results},null,2));await new Promise<void>(r=>server.close(()=>r()));}
