import {createServer} from 'node:http';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import assert from 'node:assert/strict';
import {ControlledBrowser} from '../BE/src/browser/controlled';
import {AgentRunner} from '../BE/src/agent/runner';
import {OpenAIPlanner} from '../BE/src/providers/openai';
import {config,safeError} from '../BE/src/config';
import {bolnaDemoProfile} from '../BE/src/sites/bolna-demo';
import type {Session} from '../shared/types';
config.headless=true;config.allowLocalTests=true;
const html=await readFile('tests/fixtures/bolna-creation.html','utf8');
const server=createServer((_req,res)=>{res.writeHead(200,{'Content-Type':'text/html'});res.end(html)});
await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${(server.address() as {port:number}).port}`;
const results:unknown[]=[];
const scenarios=[
 {name:'workflow-question-card',path:'/workflows',prompt:'Build a complete workflow for my business. Ask for the missing name, purpose, sequence and required inputs together before creating anything.',check:(db:any,s:Session)=>{assert.ok(s.clarification);assert.ok(s.clarification.questions.length>=2);assert.ok(s.clarification.questions.length<=6);assert.match(JSON.stringify(s.clarification),/name/i);assert.match(JSON.stringify(s.clarification),/purpose|sequence|steps|outcome|flow/i);assert.equal(s.steps,0);assert.equal(db.counts.workflowCreates,0);assert.equal(s.status,'ready');}},
 {name:'agent-question-card',path:'/dashboard',prompt:'Create an English voice agent for my business. Ask me for the missing agent name, business facts and purpose together before you create it.',check:(db:any,s:Session)=>{assert.ok(s.clarification);assert.ok(s.clarification.questions.length>=2);assert.match(JSON.stringify(s.clarification),/name/i);assert.match(JSON.stringify(s.clarification),/business|facts|purpose/i);assert.equal(s.steps,0);assert.equal(db.counts.agentCreates,0);assert.equal(s.status,'ready');}},

 {name:'agent-from-brief',path:'/dashboard',prompt:'Create and save an English agent named Nova Demo — Consultation Concierge for a fictional workshop. Open Monday to Friday 10 AM to 6 PM Asia/Kolkata, consultations last 20 minutes. Welcome the caller using {first_name}, ask whether they need hours or consultation information. Write a concise Canvas prompt using these facts; clarify uncertain requests and do not claim bookings. Set Temperature 0.4 and Output tokens 400. Retain default voice/model/routing. Do not call anyone.',check:(db:any,s:Session)=>{assert.equal(db.agents.length,1);const a=db.agents[0];assert.equal(a.name,'Nova Demo — Consultation Concierge');assert.equal(a.saved,true);assert.equal(a.temperature,0.4);assert.equal(a.tokens,400);assert.match(a.welcome,/\{first_name\}/);assert.match(a.prompt,/20|twenty/);assert.match(a.prompt,/10/);assert.equal(db.counts.saves,1);assert.equal(db.counts.agentCreates,1);assert.equal(s.status,'ready');}},
 {name:'connected-calling-workflow-draft',path:'/workflows',prompt:'Create a new workflow named Nova Demo — Consultation Journey. Keep required mobile_number input. Build Start → Agent using the existing Nova Demo — Workflow Lab → Wait for 2 minutes → End with success outcome. Name the nodes Workshop conversation, Review pause, and Journey complete. Connect every node, validate and leave unpublished. This is only configuration: do not make calls, publish or execute it.',check:(db:any,s:Session)=>{assert.equal(db.workflows.length,1);const w=db.workflows[0];assert.equal(w.name,'Nova Demo — Consultation Journey');assert.equal(w.field,'mobile_number');assert.equal(w.required,true);assert.deepEqual(w.nodes.map((n:any)=>n.kind),['Agent','Wait','End']);assert.deepEqual(w.nodes.map((n:any)=>n.name),['Workshop conversation','Review pause','Journey complete']);assert.equal(w.nodes[0].agent,'Nova Demo — Workflow Lab');assert.equal(w.nodes[1].delay,2);assert.equal(w.nodes[1].unit,'minutes');assert.equal(w.nodes[2].outcome,'success');assert.deepEqual(w.edges,[['start',w.nodes[0].id],[w.nodes[0].id,w.nodes[1].id],[w.nodes[1].id,w.nodes[2].id]]);assert.equal(db.counts.workflowCreates,1);assert.equal(s.status,'ready');assert.match(s.messages.at(-1)?.text||'',/valid|issues/i);}},
 {name:'campaign-version-and-file-handoff',path:'/campaigns',prompt:'Prepare a campaign named Nova Demo — Founder Preview using Nova Demo — No-contact Workflow Lab, Version 1 latest. I will select the CSV file myself from my computer when you reach Contacts. Configure its name, workflow and version, then stop and tell me the specific upload step remaining. Do not launch or schedule.',check:(db:any,s:Session)=>{assert.equal(db.campaigns.length,1);assert.deepEqual(db.campaigns[0],{name:'Nova Demo — Founder Preview',workflow:'Nova Demo — No-contact Workflow Lab',version:'Version 1 · latest'});assert.equal(db.counts.campaignCreates,1);assert.match(s.messages.at(-1)?.text||'',/file|upload|select/i);}},
 {name:'campaign-unpublished-dependency',path:'/campaigns',prompt:'Prepare a campaign named Nova Demo — Dependency Check using Unpublished sales draft. If it has no published version, stop and explain the missing prerequisite. Do not publish anything or launch.',check:(db:any,s:Session)=>{assert.ok(db.campaigns.length<=1);if(db.campaigns.length){assert.equal(db.campaigns[0].workflow,'Unpublished sales draft');assert.equal(db.campaigns[0].version,'Select version');}assert.match(s.messages.at(-1)?.text||'',/publish/i);assert.ok(db.counts.campaignCreates<=1);}},
];
try{for(const scenario of scenarios.filter(s=>!process.argv[2]||s.name===process.argv[2])){const driver=new ControlledBrowser();await driver.open(base+scenario.path);let approvals=0;const session:Session={id:scenario.name,siteId:'demo',mode:'browser',status:'ready',url:base+scenario.path,title:'Isolated creation fixture',messages:[],traces:[],steps:0,model:config.model,startedAt:Date.now()};const runner=new AgentRunner(session,driver,new OpenAIPlanner(),{...bolnaDemoProfile,url:base,domain:'127.0.0.1'},s=>{if(s.approval){approvals++;runner.stop(false)}});const start=Date.now();try{await runner.command(scenario.prompt);const db=await (driver as any).current().evaluate(()=>JSON.parse(localStorage.lab||'{}'));scenario.check(db,session);assert.equal(approvals,0);assert.equal(db.counts.publishes,0);assert.equal(db.counts.launches,0);results.push({name:scenario.name,ok:true,ms:Date.now()-start,steps:session.steps,usage:session.usage,reply:session.messages.at(-1)?.text,db});}catch(error){process.exitCode=1;results.push({name:scenario.name,ok:false,error:safeError(error),ms:Date.now()-start,steps:session.steps,messages:session.messages,traces:session.traces});}finally{console.log(JSON.stringify(results.at(-1),null,2));await runner.close();}}}finally{await mkdir('artifacts/bolna/founder-demo',{recursive:true});await writeFile(`artifacts/bolna/founder-demo/creation-${process.argv[2]||'all'}.json`,JSON.stringify({at:new Date().toISOString(),scope:'Isolated fictional UI with real Nova planner/controller; NOT live Bolna certification',results},null,2));await new Promise<void>(r=>server.close(()=>r()));}
