import OpenAI from 'openai';
import { WebSocket } from 'ws';
import { writeFile } from 'node:fs/promises';
import { config, safeError } from '../BE/src/config';
import { SarvamVoice } from '../BE/src/providers/sarvam';
const report:Record<string,unknown> = {at:new Date().toISOString()};
async function check(name:string, fn:()=>Promise<unknown>) {const start=performance.now();try{const details=await fn();report[name]={ok:true,ms:Math.round(performance.now()-start),details};}catch(error){report[name]={ok:false,ms:Math.round(performance.now()-start),error:safeError(error)};}console.log(name,JSON.stringify(report[name]));}
await check('openai',async()=>{const client=new OpenAI({apiKey:config.openaiKey,maxRetries:0,timeout:30000});const r=await client.responses.create({model:config.model,reasoning:{effort:'low'},input:'Reply with exactly: Nova ready.',max_output_tokens:100,store:false});if(!r.output_text)throw new Error('No output text');return {model:r.model,text:r.output_text,usage:r.usage};});
await check('sarvamConversation',async()=>{const r=await fetch('https://api.sarvam.ai/v1/chat/completions',{method:'POST',headers:{'api-subscription-key':config.sarvamKey,'Content-Type':'application/json'},body:JSON.stringify({model:config.sarvamChat,reasoning_effort:null,max_tokens:40,messages:[{role:'user',content:'Say hello in one short English sentence.'}]}),signal:AbortSignal.timeout(15000)});if(!r.ok)throw new Error(`HTTP ${r.status}`);const data=await r.json() as any;return {model:config.sarvamChat,text:data.choices?.[0]?.message?.content};});
await check('sarvamTTSStreaming',()=>new Promise((resolve,reject)=>{let bytes=0;let firstAudio=0;const start=Date.now();const voice=new SarvamVoice(event=>{if(event.event==='audio'){bytes+=Buffer.from(event.audio!,'base64').length;if(!firstAudio)firstAudio=Date.now()-start;}if(event.event==='speech-done'){clearTimeout(timer);voice.close();resolve({bytes,firstAudioMs:firstAudio,model:config.ttsModel});}if(event.event==='error'){clearTimeout(timer);voice.close();reject(new Error(event.message));}},()=>{},()=>{});const timer=setTimeout(()=>{voice.close();reject(new Error('TTS timed out'));},20000);voice.speak('Hello. I am Nova, your website companion.');}));
await check('sarvamSTTStreaming',()=>new Promise((resolve,reject)=>{const params=new URLSearchParams({model:config.sttModel,language_code:'en-IN',stream_type:'fast',encoding:'linear16',sample_rate:'16000'});const ws=new WebSocket(`wss://api.sarvam.ai/speech-to-text-realtime/ws?${params}`,{headers:{'api-subscription-key':config.sarvamKey},handshakeTimeout:10000});let done=false;const timer=setTimeout(()=>{ws.terminate();reject(new Error('STT handshake timed out'));},15000);ws.on('message',raw=>{const e=JSON.parse(raw.toString());if(e.event==='session.begin'){done=true;clearTimeout(timer);ws.send(JSON.stringify({event:'end'}));ws.close();resolve({model:config.sttModel,event:e.event});}if(e.event==='error'){clearTimeout(timer);ws.close();reject(new Error(e.message));}});ws.on('error',reject);ws.on('close',code=>{clearTimeout(timer);if(!done)reject(new Error(`STT closed ${code}`));});}));
await writeFile('BE/data/provider-report.json',JSON.stringify(report,null,2),{mode:0o600});
if(Object.values(report).some(value=>typeof value==='object'&&value!==null&&'ok' in value&&!value.ok))process.exitCode=1;
