// Disposable local UI harness. Never attaches to the user's Chrome profile.
import {build} from 'esbuild';
import {createServer} from 'node:http';
import {mkdir,readFile,writeFile} from 'node:fs/promises';
import {chromium} from 'playwright';
import assert from 'node:assert/strict';
const bundle=await build({stdin:{contents:`import React,{useState} from 'react';import{createRoot}from'react-dom/client';import{QuestionCard}from'./web/src/panel/QuestionCard';
const initial={id:'card',title:'Shape your workflow',description:'Tell me the goal. I’ll handle the steps and keep this as a draft.',status:'pending',questions:[{id:'name',label:'What should we call it?',description:'Use a name you can recognize later.',type:'text',required:true,placeholder:'e.g. Demo follow-up',options:[]},{id:'sequence',label:'What should happen?',description:'Choose a starting point or describe your own.',type:'single_choice',required:true,placeholder:'',options:[{label:'Wait, then finish',description:'A simple demo without contacting anyone.'},{label:'Use an existing agent',description:'Add an agent step to your workflow.'}]},{id:'delay',label:'How long should it wait?',description:'Time in minutes.',type:'number',required:false,placeholder:'1',options:[]}]};function App(){const[card,setCard]=useState(initial);return <div className="np-app" style={{height:'auto',minHeight:'100vh',padding:20}}><div className="np-message-author">✳ Nova · Workspace</div><QuestionCard card={card} active={card.status==='pending'} disabled={false} error="" onSubmit={answers=>{window.results.push(answers);setCard({...card,status:'answered',answers});return true}} onHelp={answers=>window.help=answers}/></div>}window.results=[];createRoot(document.getElementById('root')).render(<App/>);`,resolveDir:process.cwd(),loader:'tsx'},bundle:true,write:false,format:'iife',jsx:'automatic'});
const css=await readFile('web/src/panel/panel.css','utf8');
const server=createServer((req,res)=>{res.setHeader('Content-Type',req.url==='/bundle.js'?'application/javascript':'text/html');res.end(req.url==='/bundle.js'?bundle.outputFiles[0].text:`<!doctype html><html><meta name="viewport" content="width=device-width, initial-scale=1"><style>${css}</style><div id="root"></div><script src="/bundle.js"></script></html>`)});
await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({headless:true});
try{const page=await browser.newPage({viewport:{width:380,height:850}});const url=`http://127.0.0.1:${(server.address() as {port:number}).port}`;await page.goto(url);
 await page.getByRole('button',{name:'Continue',exact:true}).click();assert.equal(await page.getByRole('alert').count(),2);assert.equal(await page.evaluate(()=>document.activeElement?.getAttribute('aria-label')),'What should we call it?');
 await page.getByLabel('What should we call it?').fill('Project — Guided Workflow');await page.getByRole('radio',{name:/Wait, then finish/}).click();await page.getByRole('button',{name:'Help me choose'}).click();assert.equal(await page.evaluate(()=>(window as any).help[0].values[0]),'Project — Guided Workflow');assert.equal(await page.getByLabel('What should we call it?').inputValue(),'Project — Guided Workflow');
 await page.getByLabel('How long should it wait?').fill('wrong');await page.getByRole('button',{name:'Continue',exact:true}).click();assert.match(await page.getByRole('alert').innerText(),/valid number/);await page.getByLabel('How long should it wait?').fill('1');
 await mkdir('artifacts/core',{recursive:true});await page.screenshot({path:'artifacts/core/question-card.png',fullPage:true});
 await page.setViewportSize({width:320,height:740});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.getByRole('button',{name:'Something else +'}).click();await page.getByLabel('What should happen? — your answer').fill('Wait one minute, then end successfully');await page.getByRole('button',{name:'Continue',exact:true}).click();await page.getByText('Answered',{exact:true}).waitFor();await page.locator('summary').click();assert.match(await page.locator('details').innerText(),/Wait one minute/);assert.equal(await page.evaluate(()=>(window as any).results.length),1);
 const report={ok:true,checks:['required fields and focus','numeric validation','partial answers retained on help','no default selection','custom choice replaces single choice','320px no overflow','submitted answers receipt','one submit']};await writeFile('artifacts/core/question-card-ui.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report));
}finally{await browser.close();await new Promise<void>(r=>server.close(()=>r()));}
