import React, { useEffect, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowUp, ArrowUpRight, AudioLines, Check, CheckCheck, ChevronDown, ChevronRight, CircleHelp, Clock3, Copy, ExternalLink, Globe2, LayoutGrid, Loader2, Mic, MicOff, MoreHorizontal, Play, Plus, Search, Settings2, ShieldCheck, Sparkles, Square, Workflow, X, Zap, Link2, Radio, Cable, History, BookOpen, RefreshCw, CheckCircle2 } from 'lucide-react';
import { isExtension, useNova } from './useNova';
import { browserExtensionReady, openWebsiteTab } from './browser-launch';
import type { Session, SiteProfile, Flow } from '../../shared/types';
import './styles.css';
import { ExtensionSetup } from './ExtensionSetup';

type Nova = ReturnType<typeof useNova>;
function Mark({ size = 30 }: { size?: number }) { return <svg width={size} height={size} viewBox="0 0 64 64" aria-hidden="true"><g fill="currentColor"><ellipse cx="32" cy="32" rx="9" ry="27"/><ellipse cx="32" cy="32" rx="9" ry="27" transform="rotate(60 32 32)"/><ellipse cx="32" cy="32" rx="9" ry="27" transform="rotate(120 32 32)"/></g><circle cx="32" cy="32" r="6" fill="var(--mark-center,#f7f7f2)"/></svg>; }
function SiteIcon({ site, large = false }: { site: Pick<SiteProfile, 'id' | 'color' | 'name'>; large?: boolean }) {
  return <span className={`site-icon ${large ? 'large' : ''}`} style={{ '--site': site.color } as React.CSSProperties}>{site.id === 'amazon' ? <span className="amazon-logo">a<span>⌣</span></span> : site.id === 'youtube' ? <span className="youtube-logo"><Play size={16} fill="white" strokeWidth={0}/></span> : site.id === 'google' ? <span className="google-logo">G</span> : <Globe2 size={large ? 25 : 20}/>}</span>;
}
const timeAgo = (time: number) => { const mins = Math.max(0, Math.floor((Date.now() - time) / 60000)); return mins < 1 ? 'Just now' : mins < 60 ? `${mins}m ago` : `${Math.floor(mins / 60)}h ago`; };


function App() {
  const nova = useNova(); const [view, setView] = useState(() => location.hash === '#setup' ? 'settings' : 'overview'); const [modal, setModal] = useState(false); const [editing, setEditing] = useState<SiteProfile>(); const [launching, setLaunching] = useState(''); const [query, setQuery] = useState(''); const [speed, setSpeed] = useState('intelligent');
  useEffect(() => { history.replaceState(null, '', view === 'settings' ? '#setup' : location.pathname + location.search); }, [view]);
  useEffect(() => { const change = () => { if (location.hash === '#setup') setView('settings'); }; window.addEventListener('hashchange', change); return () => window.removeEventListener('hashchange', change); }, []);
  const [browserReady, setBrowserReady] = useState(false);
  useEffect(() => {
    let active = true;
    const check = () => { void browserExtensionReady().then(ready => { if (active) setBrowserReady(ready); }); };
    check(); window.addEventListener('focus', check);
    return () => { active = false; window.removeEventListener('focus', check); };
  }, []);
  const launch = async (site: SiteProfile) => {
    setLaunching(site.id); nova.setError('');
    try {
      if (!await browserExtensionReady()) {
        setBrowserReady(false); setView('settings');
        throw new Error('Add or reload Nova’s extension in this browser, then refresh this dashboard. Websites will open in a new tab in this same window.');
      }
      setBrowserReady(true); await openWebsiteTab(site.url, speed);
    } catch (e) { nova.setError((e as Error).message); } finally { setLaunching(''); }
  };
  const demo = async () => { try { const site = await nova.api<SiteProfile>('/sites', { url: 'http://127.0.0.1:8787/demo/shop', name: 'Nova Demo Shop', instructions: 'This is a local demonstration shop with fictional products and prices. No real orders or payments are possible. Search, inspect a product, ask before adding to cart, and verify the cart count.' }); await nova.refreshSites(); await launch(site); } catch(e) { nova.setError((e as Error).message); } };
  const sessionList = <div className="session-list">{nova.sessions.length === 0 ? <div className="empty-state"><div className="empty-icon"><Clock3 size={22}/></div><h3>A fresh start.</h3><p>Connect to a website and your sessions will appear here.</p><button className="text-button" onClick={() => setView('sites')}>Explore your websites <ArrowUpRight size={14}/></button></div> : nova.sessions.slice().reverse().map(session => { const site = nova.sites.find(s => s.id === session.siteId); return <button key={session.id} className="session-row" onClick={() => void nova.api(`/sessions/${session.id}/focus`, {}, 'POST').catch(e => nova.setError(e.message))}><SiteIcon site={site || { id: '', name: 'Website', color: '#7360db' }}/><div><strong>{session.messages.find(m => m.role === 'user')?.text || `Ready on ${site?.name || 'your website'}`}</strong><span>{site?.name} · {session.steps} actions · {timeAgo(session.startedAt)}</span></div><span className={`session-status ${session.status}`}>{session.status === 'running' ? 'Working' : session.status === 'approval' ? 'Needs you' : session.status}</span><ChevronRight size={16}/></button>; })}</div>;
  return <div className="app-shell">
    <aside className="sidebar"><a className="brand" href="#" onClick={e => { e.preventDefault(); setView('overview'); }}><Mark size={31}/><span>nova<span className="brand-period">.</span></span></a><div className="workspace-switch"><span className="workspace-avatar">Y</span><span>Your workspace<small>Personal</small></span></div>
      <span className="nav-caption">WORKSPACE</span><nav>{[{id:'overview',label:'Overview',icon:LayoutGrid},{id:'sites',label:'Your websites',icon:Globe2},{id:'activity',label:'Activity',icon:Clock3},{id:'flows',label:'Flow library',icon:Workflow}].map(item => <button key={item.id} aria-label={item.label} className={view === item.id ? 'selected' : ''} onClick={() => setView(item.id)}><item.icon size={18}/><span>{item.label}</span>{item.id === 'sites' && <span className="nav-count">{nova.sites.length}</span>}</button>)}</nav>
      <div className="sidebar-note"><span className="note-star">✳</span><h4>Less clicking.<br/>More doing.</h4><p>Your next idea is only<br/>a conversation away.</p><button onClick={() => void demo()}>Try the demo <ArrowUpRight size={14}/></button></div>
      <div className="sidebar-bottom"><button aria-label="Settings & setup" onClick={() => setView('settings')} className={view === 'settings' ? 'selected' : ''}><Settings2 size={18}/> Settings & setup</button><button aria-label="Getting started" onClick={() => setView('guide')}><CircleHelp size={18}/> Getting started</button><div className="user-row"><span className="user-avatar">Y</span><div><strong>Your personal space</strong><small>Local workspace</small></div><span className={`status-dot ${nova.connected ? '' : 'gray'}`}/></div></div>
    </aside>
    <div className="main-shell"><header className="topbar"><div><span>Workspace</span><ChevronRight size={13}/><strong>{{overview:'Overview',sites:'Your websites',activity:'Activity',flows:'Flow library',settings:'Settings & setup',guide:'Getting started'}[view]}</strong></div><div className="topbar-right"><span className="local-badge"><span className={`status-dot ${nova.connected ? '' : 'gray'}`}/>{nova.connected ? 'Nova is online' : 'Connecting'}</span><span className="top-avatar">Y</span></div></header>
    <main className="main-content">
      {nova.error && <div className="error-banner" role="alert"><span>{nova.error}</span>{!nova.connected && <button onClick={() => nova.config ? nova.connect(nova.config.token) : location.reload()}><RefreshCw size={14}/> Reconnect</button>}<button aria-label="Dismiss error" onClick={() => nova.setError('')}><X size={16}/></button></div>}
      {view === 'overview' && <><div className="page-heading"><div><p className="eyebrow">A LITTLE HELP GOES A LONG WAY</p><h1>Welcome to your lighter day<span>.</span></h1><p>Your websites. Your voice. A companion that gets things done.</p></div><button className="button primary" onClick={() => setModal(true)}><Plus size={16}/> Add a website</button></div>
        {!browserReady && <div className="info-strip"><Cable size={19}/><div><strong>Bring Nova into your browser.</strong><p>Download the extension and follow the one-time setup to get started.</p></div><button className="text-button" onClick={() => setView('settings')}>Download & set up <ArrowUpRight size={15}/></button></div>}
        <section className="hero"><div className="hero-copy"><span className="hero-tag"><span/> MEET YOUR WEB COMPANION</span><h2>You say it.<br/>Nova takes it<br/><em>from here.</em></h2><p>Find that perfect product. Discover your next<br className="wide-only"/> favorite video. Make the everyday feel effortless.</p><button className="button dark" onClick={() => setView('sites')}>Let’s do something <ArrowUpRight size={17}/></button><span className="hero-footnote"><Mic size={13}/> Built for conversation, ready for action.</span></div><div className="hero-art" aria-hidden="true"><div className="orbit orbit-one"/><div className="orbit orbit-two"/><div className="orbit orbit-three"/><div className="orb-glow"/><div className="main-orb"><div className="orb-highlight"/><Mark size={107}/></div><span className="art-spark s1">✦</span><span className="art-spark s2">✧</span><span className="art-spark s3">✦</span><div className="floating-card voice-card"><span className="floating-icon"><AudioLines size={21}/></span><div>“Find it for me, Nova.”<small>Your voice is the shortcut.</small></div></div><div className="floating-card action-card"><span className="small-check"><Check size={13}/></span><span>A little help, right here.</span></div><div className="orbit-dot"/></div></section>
        <div className="section-heading"><div><h2>Your websites <span>{nova.sites.length}</span></h2><p>A familiar companion, wherever you go.</p></div><button className="text-button" onClick={() => setView('sites')}>View all <ArrowUpRight size={15}/></button></div><div className="site-grid">{nova.sites.slice(0,3).map(site => <SiteCard key={site.id} site={site} loading={launching === site.id} disabled={!!launching || !nova.connected} onLaunch={() => void launch(site)} onEdit={() => setEditing(site)}/>)}</div>
        <div className="section-heading activity-heading"><div><h2>Pick up where you left off</h2><p>Return to Nova on the website where you left off.</p></div><button className="text-button" onClick={() => setView('activity')}>All activity <ArrowUpRight size={15}/></button></div>{sessionList}
        <div className="trust-line"><ShieldCheck size={15}/><span>Always your companion. Always your call.</span><i/> Nova checks with you before consequential actions.</div>
      </>}
      {view === 'sites' && <><div className="page-heading"><div><p className="eyebrow">ONE COMPANION. MANY POSSIBILITIES.</p><h1>Your websites<span>.</span></h1><p>Give Nova a home on the websites you use.</p></div><button className="button primary" onClick={() => setModal(true)}><Plus size={16}/> Add a website</button></div><div className="filter-row"><label className="search-field"><Search size={17}/><input placeholder="Find a website…" value={query} onChange={e => setQuery(e.target.value)}/></label><label className="speed-select"><Zap size={15}/><select value={speed} onChange={e => setSpeed(e.target.value)}><option value="intelligent">Quality</option><option value="fast">Lower cost</option></select></label></div><div className="site-grid full-grid">{nova.sites.filter(s => `${s.name} ${s.domain}`.toLowerCase().includes(query.toLowerCase())).map(site => <SiteCard key={site.id} site={site} loading={launching === site.id} disabled={!!launching || !nova.connected} onLaunch={() => void launch(site)} onEdit={() => setEditing(site)}/>)}<button className="add-site-card" onClick={() => setModal(true)}><span><Plus size={24}/></span><strong>Make yourself at home.</strong><p>Add any public website URL.</p></button></div><div className="info-strip"><Cable size={19}/><div><strong>Keep your browser. Keep your sign-in.</strong><p>Open websites beside this dashboard with the Nova extension in this browser.</p></div><button className="text-button" onClick={() => setView('settings')}>Set up extension <ArrowUpRight size={15}/></button></div></>}
      {view === 'activity' && <><div className="page-heading"><div><p className="eyebrow">A LITTLE PROGRESS, EVERY DAY</p><h1>Your activity<span>.</span></h1><p>Live sessions and the steps Nova has taken with you.</p></div></div>{sessionList}{nova.sessions.length > 0 && <div className="session-management">{nova.sessions.map(s => <div key={s.id} data-session-id={s.id}><span>{s.title}</span><button className="text-button" onClick={() => { void nova.api(`/sessions/${s.id}`, undefined, 'DELETE').catch(e => nova.setError(e.message)); }}>End session <X size={13}/></button></div>)}</div>}</>}
      {view === 'flows' && <><div className="page-heading"><div><p className="eyebrow">TEACH ONCE. ADAPT EVERY TIME.</p><h1>A little local knowledge<span>.</span></h1><p>Give Nova the context and steps that make each website yours.</p></div></div><div className="flow-grid">{nova.sites.map(site => <section className="flow-site" key={site.id}><header><SiteIcon site={site}/><h3>{site.name}</h3><button className="icon-button" aria-label={`Edit ${site.name} flows`} onClick={() => setEditing(site)}><Settings2 size={16}/></button></header>{site.flows.map(flow => <div className="flow-item" key={flow.id}><Workflow size={17}/><div><strong>{flow.name}</strong><small>{flow.steps.length} suggested steps · {flow.verified ? 'Marked verified' : 'Needs live validation'}</small></div><ChevronRight size={15}/></div>)}<button className="flow-add" onClick={() => setEditing(site)}><Plus size={14}/> Add or edit flows</button></section>)}</div><p className="subtle-note">Flows guide Nova’s decisions. It checks the current page at every step, so a guide is never mistaken for a guaranteed outcome.</p></>}
      {view === 'settings' && <><div className="page-heading"><div><p className="eyebrow">MAKE NOVA YOURS</p><h1>Behind the scenes<span>.</span></h1><p>Your local connection, models, and browser setup.</p></div></div><ExtensionSetup nova={nova} connected={browserReady} onConnectionChange={setBrowserReady} onTryDemo={() => void demo()} launching={!!launching}/><div className="settings-card"><h3><Sparkles size={19}/> Intelligence & voice</h3><div className="setting-row"><span>Browser intelligence<small>OpenAI · Low reasoning effort</small></span><code>{nova.config?.model || 'Loading…'}</code></div><div className="setting-row"><span>Lower-cost model<small>Select when launching a website session</small></span><code>{nova.config?.fastModel}</code></div><div className="setting-row"><span>English conversation<small>Sarvam · Natural acknowledgements</small></span><code>{nova.config?.voice.chat}</code></div><div className="setting-row"><span>Speech recognition</span><code>{nova.config?.voice.stt}</code></div><div className="setting-row"><span>Speaking voice<small>{nova.config?.voice.speaker} · English (India)</small></span><code>{nova.config?.voice.tts}</code></div><div className="provider-status"><span className="status-dot"/>{nova.config?.providers.openai ? 'OpenAI key configured' : 'OpenAI key missing'}<span className="status-dot"/>{nova.config?.providers.sarvam ? 'Sarvam key configured' : 'Sarvam key missing'}</div><p className="subtle-note">Provider secrets stay in the backend .env file. “Configured” means a key is present; live requests determine access and quota.</p></div></>}
      {view === 'guide' && <><div className="page-heading"><div><p className="eyebrow">A GOOD PLACE TO BEGIN</p><h1>Meet your everyday companion<span>.</span></h1><p>Three steps from a website to a little less work.</p></div></div><div className="guide-grid">{[{n:'01',icon:Globe2,title:'Choose a website',text:'Start with Amazon, YouTube, Google, or add a public URL. The website opens in a new tab in this browser, with Nova’s floating button after you enable access.'},{n:'02',icon:Workflow,title:'Make it familiar',text:'Add site instructions and flows. Nova uses these alongside the page it can actually see.'},{n:'03',icon:Mic,title:'Tell Nova what you need',text:'Click Nova on the website to open its browser side panel. Chat is ready first; switch to Live voice to speak. Follow the cursor as Nova handles the page.'}].map(x => <div className="guide-card" key={x.n}><span>{x.n}</span><x.icon size={28}/><h3>{x.title}</h3><p>{x.text}</p></div>)}</div><div className="settings-card"><h3>Try it without a real transaction.</h3><p>The demo shop has fictional products and a test cart. It exercises searching, reading details, confirmations, and checking results.</p><button className="button primary" onClick={() => void demo()} disabled={!!launching}><Play size={15}/> {launching ? 'Opening…' : 'Open demo shop'}</button></div><div className="settings-card"><h3>When Nova needs you</h3><p>Sign in, enter payment details, and complete human verification directly in the browser. Protected pages, cross-origin frames, inaccessible controls, and website changes can need your help. A website guide does not give Nova knowledge of pages it has never seen.</p></div></>}
    </main><footer className="workspace-footer"><span>Made for a more human web.</span><span><Mark size={12}/> nova.</span></footer></div>
    {modal && <AddSiteModal nova={nova} onClose={() => setModal(false)}/>}
    {editing && <FlowModal nova={nova} site={editing} onClose={() => setEditing(undefined)}/>}
    {launching && <div className="launch-toast"><Loader2 size={18} className="spin"/><div><strong>Opening your website</strong><span>Opening a new tab in this browser…</span></div></div>}
  </div>;
}

function SiteCard({ site, loading, disabled, onLaunch, onEdit }: { site: SiteProfile; loading: boolean; disabled: boolean; onLaunch(): void; onEdit(): void }) { return <article className="site-card"><div className="site-card-top"><SiteIcon site={site} large/><button className="icon-button" aria-label={`Configure ${site.name}`} onClick={onEdit}><MoreHorizontal size={19}/></button></div><h3>{site.name}</h3><span className="site-domain">{site.domain}</span><p>{site.description}</p><div className="site-card-bottom"><span><Workflow size={13}/>{site.flows.length} flows</span><button onClick={onLaunch} disabled={disabled}>{loading ? <Loader2 size={14} className="spin"/> : <>Open with Nova <ArrowUpRight size={15}/></>}</button></div></article>; }

function AddSiteModal({ nova, onClose }: { nova: Nova; onClose(): void }) {
  const [url,setUrl] = useState(''); const [name,setName] = useState(''); const [instructions,setInstructions] = useState(''); const [saving,setSaving] = useState(false); const [error,setError] = useState('');
  return <div className="modal-backdrop" onClick={e => { if(e.target === e.currentTarget) onClose(); }}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="add-title"><button className="modal-close icon-button" aria-label="Close" onClick={onClose}><X size={20}/></button><span className="modal-symbol"><Globe2 size={25}/></span><h2 id="add-title">A new place for Nova.</h2><p>Add a website. Give it a little context.<br/>Nova will get to know the page when you connect.</p><form onSubmit={e => { e.preventDefault(); setSaving(true); void nova.api('/sites',{url,name:name || undefined,instructions}).then(() => nova.refreshSites()).then(onClose).catch(e => setError(e.message)).finally(() => setSaving(false)); }}><label>Website URL<input autoFocus placeholder="https://your-website.com" value={url} onChange={e => setUrl(e.target.value)} required/></label><label>Display name <span>Optional</span><input placeholder="A familiar name" value={name} onChange={e => setName(e.target.value)}/></label><label>What should Nova know? <span>Optional</span><textarea placeholder="What you do here, important preferences, or useful context…" rows={3} value={instructions} onChange={e => setInstructions(e.target.value)}/></label>{error && <p className="form-error">{error}</p>}<button className="button primary full-width" disabled={saving || !url.trim()}>{saving ? <Loader2 size={16} className="spin"/> : <Plus size={16}/>} Add website</button></form><small className="modal-note">No website code changes needed. Install the Nova extension in this browser to use its floating assistant.</small></section></div>;
}
function FlowModal({ nova, site, onClose }: { nova: Nova; site: SiteProfile; onClose(): void }) {
  const [name,setName] = useState(site.name); const [description,setDescription] = useState(site.description); const [instructions,setInstructions] = useState(site.instructions); const [color,setColor] = useState(site.color); const [flows,setFlows] = useState<Flow[]>(structuredClone(site.flows)); const [saving,setSaving] = useState(false); const [error,setError] = useState('');
  return <div className="modal-backdrop"><section className="modal flow-modal" role="dialog" aria-modal="true" aria-labelledby="flow-title"><button className="modal-close icon-button" aria-label="Close" onClick={onClose}><X size={20}/></button><h2 id="flow-title">Make Nova feel at home.</h2><p>Choose the introduction, accent, and useful tasks for this website. Nova can also handle requests outside these guides.</p><form onSubmit={e => { e.preventDefault(); setSaving(true); void nova.api(`/sites/${site.id}`,{name,description,instructions,color,flows},'PATCH').then(() => nova.refreshSites()).then(onClose).catch(e => setError(e.message)).finally(() => setSaving(false)); }}><div className="form-row"><label>Website name<input value={name} onChange={e => setName(e.target.value)} required/></label><label>Accent<input type="color" value={color} onChange={e => setColor(e.target.value)}/></label></div><label>Companion introduction<textarea rows={2} maxLength={220} value={description} onChange={e => setDescription(e.target.value)} placeholder="How should Nova introduce itself on this website?"/></label><label>Site instructions<textarea rows={4} value={instructions} onChange={e => setInstructions(e.target.value)}/></label><div className="flow-editor-heading"><strong>Suggested tasks & guides</strong><button type="button" className="text-button" onClick={() => setFlows([...flows,{id:crypto.randomUUID(),name:'New flow',trigger:'',steps:[''],verified:false}])}><Plus size={14}/> Add flow</button></div>{flows.map((flow,i) => <div className="flow-editor" key={flow.id}><div><input aria-label="Flow name" value={flow.name} onChange={e => setFlows(flows.map((f,j) => j === i ? {...f,name:e.target.value,verified:false} : f))} required/><button type="button" className="icon-button" aria-label={`Remove ${flow.name}`} onClick={() => setFlows(flows.filter((_,j) => j!==i))}><X size={15}/></button></div><input aria-label="When to use this flow" placeholder="When should Nova use this flow?" value={flow.trigger} onChange={e => setFlows(flows.map((f,j) => j===i ? {...f,trigger:e.target.value,verified:false} : f))}/><textarea aria-label="Flow steps" placeholder="One step per line" rows={3} value={flow.steps.join('\n')} onChange={e => setFlows(flows.map((f,j) => j===i ? {...f,steps:e.target.value.split('\n'),verified:false} : f))}/></div>)}{error && <p className="form-error">{error}</p>}<button className="button primary full-width" disabled={saving}>{saving ? <Loader2 size={16} className="spin"/> : <Check size={16}/>} Save website knowledge</button></form></section></div>;
}
createRoot(document.getElementById('root')!).render(<App/>);
